name: CI

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build with Gradle
        run: |
          chmod +x gradlew   # Добавляем исполняемые права для gradlew
          ./gradlew build
        working-directory: ./   # Убедитесь, что вы в правильной директории проекта

      - name: Generate Jacoco report
        run: |
          chmod +x gradlew
          ./gradlew jacocoTestReport
        working-directory: ./   # Убедитесь, что вы в правильной директории проекта

      - name: Check coverage and publish
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ./build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80

      - name: Generate javadoc
        run: |
          chmod +x gradlew
          ./gradlew javadoc
        working-directory: ./   # Убедитесь, что вы в правильной директории проекта

      - name: Publish javadoc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true
          folder: ./build/docs/javadoc
          target-folder: ${{ github.event.pull_request.title }}

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: .github/google_checks.xml
          reporter: github-pr-check
